#!/usr/bin/env python
from argparse import ArgumentParser
from datetime import datetime
import os


REPO_DIR = os.path.dirname(os.path.realpath(__file__))
VIM_DIR_PATH = os.path.join(REPO_DIR, 'vim')
VIMRC_PATH = os.path.join(VIM_DIR_PATH, 'vimrc')
TMUX_PATH = os.path.join(REPO_DIR, 'tmux.conf')

PYENV_REPO = 'https://github.com/yyuu/pyenv.git'
PYENV_VIRTUALENV_REPO = 'https://github.com/yyuu/pyenv-virtualenv.git'


def install(install_dir, shell_file):
    ''' Install .vim/ + .vimrc
    Install .tmux.conf
    Setup pyenv + pyenv-virtualenv
    '''

    install_dir = os.path.realpath(install_dir)
    shell_file = os.path.join(install_dir, shell_file)
    if not os.path.isfile(shell_file):
        with open(shell_file, 'w+') as f:
            now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            f.write('# file generated by denv at %s\n' % now)

    # aliases
    with open(shell_file, 'a') as f:
        f.write('\n# aliases\n')
        f.write('alias rst="exec $SHELL; reset"\n')

        f.write('\n## git aliases\n')
        f.write('alias gst="git status"\n')

    # vim
    vim_dir_target = os.path.join(install_dir, '.vim')
    os.system('ln -s %s %s' % (VIM_DIR_PATH, vim_dir_target))

    vimrc_target = os.path.join(install_dir, '.vimrc')
    os.system('ln -s %s %s' % (VIMRC_PATH, vimrc_target))

    # tmux
    tmux_target = os.path.join(install_dir, '.tmux.conf')
    os.system('ln -s %s %s' % (TMUX_PATH, tmux_target))

    # pyenv + pyenv-virtualenv
    pyenv_target = os.path.join(install_dir, '.pyenv')
    os.system('git clone %s %s' % (PYENV_REPO, pyenv_target))

    pyenv_virtualenv_target = os.path.join(pyenv_target, 'plugins', 'pyenv-virtualenv')
    os.system('git clone %s %s' % (PYENV_VIRTUALENV_REPO, pyenv_virtualenv_target))

    with open(shell_file, 'a') as f:
        f.write('\n# pyenv + pyenv-virtualenv\n')
        f.write('export PYENV_ROOT="%s"\n' % pyenv_target)
        f.write('export PATH="$PYENV_ROOT/bin:$PATH"\n')
        f.write('eval "$(pyenv init -)"\n')
        f.write('eval "$(pyenv virtualenv-init -)"\n')


if __name__ == '__main__':
    arg_parser = ArgumentParser()
    arg_parser.add_argument('-i', '--install-dir', type=str,
        help='specify the install directory')
    arg_parser.add_argument('-s', '--shell-file', type=str,
        help='specify the shell file')
    args = arg_parser.parse_args()

    install_dir = args.install_dir or os.environ['HOME']
    shell_file = args.shell_file or '.bashrc'
    install(install_dir, shell_file)

